#!/bin/bash
#
# WAV to {FLAC | MP3} converter
# Smart converter from WAV to FLAC and/or MP3 format
#
# Requires: flac and/or lame
#
# Copyright © 2015 Mark Karpov
#
# wav2 is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# wav2 is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

### constants

LONG_OPTS="help,flac,mp3,count,output:,indexing,artist:,title:,\
year:,comment:,license,version"
SHORT_OPTS="FMco:ia:t:y:m:h"
WAV2_VERSION="0.1.0"

### variables: options

convert_to_flac=0
convert_to_mp3=0
count_total_tracks=0
output_directory=
parse_track_index=0
tag_album_artist=
tag_album_title=
tag_album_year=
tag_comment=

### variables: other

files=

### functions

bad_exit() # prints error message and exits the program
{
    echo "$(basename $0): ${1:-"Unknown Error"}"  1>&2
    exit 1
}

usage()
{
    cat << EOF
wav2 — convert WAV files into FLAC and/or MP3 format

Usage: wav2 [OPTIONS] [FILES]

Available options:
  -h,--help                Show this help text
  -F,--flac                Convert FILES into FLAC format
  -M,--mp3                 Convert FILES into MP3 format
  -c,--count               Count number of FILES and write it as tag
  -o,--output OUT          Save converted files in OUT directory
  -i,--indexing            Parse numeric prefix of files and write as tag
  -a,--artist STR          Write STR as «album artist» tag
  -t,--title STR           Write STR as «album title» tag
  -y,--year STR            Write STR as «year» tag
  -m,--comment STR         Write STR as «comment» tag
  --license                Show license of the program
  --version                Show version of the program
EOF
}

license()
{
    cat << EOF
WAV2 — convert WAV files into FLAC and/or MP3 format.
Copyright © 2015 Mark Karpov

WAV2 is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

WAV2 is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <http://www.gnu.org/licenses/>.
EOF
}

version()
{
    echo "WAV2 $WAV2_VERSION"
}

parse_opts()
{
    getopt -T
    test $? -ne 4 && bad_exit "Need enhanced version of \`getopt\' to function."
    local parsed_options=$(getopt --name "wav2" --options $SHORT_OPTS \
                                  --longoptions $LONG_OPTS -- "$@")
    test $? -ne 0 && bad_exit "parsing of command line options failed."
    eval set -- "$parsed_options"
    while test "$1" != ""; do
        case "$1" in
            -h | --help     ) usage
                              exit
                              ;;
            -F | --flac     ) convert_to_flac=1
                              ;;
            -M | --mp3      ) convert_to_mp3=1
                              ;;
            -c | --count    ) count_total_tracks=1
                              ;;
            -o | --output   ) shift
                              output_directory="$1"
                              ;;
            -i | --indexing ) parse_track_index=1
                              ;;
            -a | --artist   ) shift
                              tag_album_artist="$1"
                              ;;
            -t | --title    ) shift
                              tag_album_title="$1"
                              ;;
            -y | --year     ) shift
                              tag_album_year="$1"
                              ;;
            -m | --comment  ) shift
                              tag_comment="$1"
                              ;;
            --license       ) license
                              exit
                              ;;
            --version       ) version
                              exit
                              ;;
            --              ) shift
                              files="$@"
                              break
                              ;;
            ?               ) bad_exit "parsing error."
        esac
        shift
    done
}

### main

parse_opts $@

echo "Convert to FLAC:    $convert_to_flac"
echo "Convert to MP3:     $convert_to_mp3"
echo "Count total tracks: $count_total_tracks"
echo "Output directory:   $output_directory"
echo "Parse track number: $parse_track_index"
echo "Album artist:       $tag_album_artist"
echo "Album title:        $tag_album_title"
echo "Album year:         $tag_album_year"
echo "Comment:            $tag_comment"
echo "Files to process:   $files"
