#!/bin/bash
#
# WAV to {FLAC | MP3} converter
# Smart converter from WAV to FLAC and/or MP3 format
#
# Requires: flac and/or lame
#
# Copyright © 2015 Mark Karpov
#
# wav2 is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# wav2 is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

### constants

LONG_OPTS="help,flac,mp3,count,output:,indexing,album:,artist:,comment:,\
genre:,year:,license,version"
SHORT_OPTS="hFMno:il:a:c:g:y:"
WAV2_VERSION="0.1.0"

### variables: options

convert_to_flac=0
convert_to_mp3=0
count_tracks=0
output_dir=
parse_index=0
tag_album=
tag_artist=
tag_comment=
tag_genre=
tag_year=

### variables: other

files=
files_number=0

### functions

bad_exit() # prints error message and exits the program
{
    echo "$(basename $0): ${1:-"unknown error"}"  1>&2
    exit 1
}

usage()
{
    cat << EOF
wav2 — convert WAV files into FLAC and/or MP3 format

Usage: wav2 [OPTIONS] [FILES]

Available options:
  -h,--help                Show this help text
  -F,--flac                Convert FILES into FLAC format
  -M,--mp3                 Convert FILES into MP3 format
  -n,--count               Count number of FILES and write it as tag
  -o,--output OUT          Save converted files in OUT directory
  -i,--indexing            Parse numeric prefix of files and write as tag
  -l,--album STR           Write STR as «album» tag
  -a,--artist STR          Write STR as «artist» tag
  -c,--comment STR         Write STR as «comment» tag
  -g,--genre STR           Write STR as «genre» tag
  -y,--year STR            Write STR as «year» tag
  --license                Show license of the program
  --version                Show version of the program
EOF
}

license()
{
    cat << EOF
WAV2 — convert WAV files into FLAC and/or MP3 format.
Copyright © 2015 Mark Karpov

WAV2 is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

WAV2 is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <http://www.gnu.org/licenses/>.
EOF
}

version()
{
    echo "WAV2 $WAV2_VERSION"
}

parse_opts()
{
    getopt -T
    test $? -ne 4 && bad_exit "Need enhanced version of \`getopt' to function."
    local parsed_options=$(getopt --name "wav2" --options $SHORT_OPTS \
                                  --longoptions $LONG_OPTS -- "$@")
    test $? -ne 0 && bad_exit "parsing of command line options failed."
    eval set -- "$parsed_options"
    while test "$1" != ""
    do
        case "$1" in
            -h | --help     ) usage
                              exit
                              ;;
            -F | --flac     ) convert_to_flac=1
                              ;;
            -M | --mp3      ) convert_to_mp3=1
                              ;;
            -n | --count    ) count_tracks=1
                              ;;
            -o | --output   ) shift
                              output_dir="$1"
                              ;;
            -i | --indexing ) parse_index=1
                              ;;
            -l | --album    ) shift
                              tag_album="$1"
                              ;;
            -a | --artist   ) shift
                              tag_artist="$1"
                              ;;
            -c | --comment  ) shift
                              tag_comment="$1"
                              ;;
            -g | --genre    ) shift
                              tag_genre="$1"
                              ;;
            -y | --year     ) shift
                              tag_year="$1"
                              ;;
            --license       ) license
                              exit
                              ;;
            --version       ) version
                              exit
                              ;;
            --              ) shift
                              files=("$@")
                              files_number=$#
                              break
                              ;;
            ?               ) bad_exit "parsing error."
        esac
        shift
    done
}

process_flac()
{
    local base_name=$(basename -s .wav "$1")
    cmd="flac -8 --force"
    if test $parse_index -ne 0
    then
        local index=
        local name=
        IFS=' '
        read -r index name <<< "$base_name"
        cmd="$cmd -T \"TRACKNUMBER=$index\""
        cmd="$cmd -T \"TITLE=$name\""
    else
        cmd="$cmd -T \"TITLE=$base_name\""
    fi
    test $count_tracks -ne 0 && cmd="$cmd -T \"TRACKTOTAL=$files_number\""
    test -n "$tag_album"     && cmd="$cmd -T \"ALBUM=$tag_album\""
    test -n "$tag_artist"    && cmd="$cmd -T \"ARTIST=$tag_artist\""
    test -n "$tag_comment"   && cmd="$cmd -T \"COMMENT=$tag_comment\""
    test -n "$tag_genre"     && cmd="$cmd -T \"GENRE=$tag_genre\""
    test -n "$tag_year"      && cmd="$cmd -T \"DATE=$tag_year\""
    test -n "$output_dir"    && cmd="$cmd -o \"$output_dir/$base_name.flac\""
    cmd="$cmd \"$1\""
    eval $cmd
}

process_mp3()
{
    local base_name=$(basename -s .wav "$1")
    cmd="lame -b 320 -h --add-id3v2"
    if test $parse_index -ne 0
    then
        local index=
        local name=
        IFS=' '
        read -r index name <<< "$base_name"
        cmd="$cmd --tt \"$name\""
        if test $count_tracks -ne 0
        then
            cmd="$cmd --tn $index/$files_number"
        else
            cmd="$cmd --tn $index"
        fi
    else
        cmd="$cmd --tt \"$base_name\""
    fi
    test -n "$tag_album"     && cmd="$cmd --tl \"$tag_album\""
    test -n "$tag_artist"    && cmd="$cmd --ta \"$tag_artist\""
    test -n "$tag_comment"   && cmd="$cmd --tc \"$tag_comment\""
    test -n "$tag_genre"     && cmd="$cmd --tg \"$tag_genre\""
    test -n "$tag_year"      && cmd="$cmd --ty \"$tag_year\""
    cmd="$cmd \"$1\" \"$output_dir/$base_name.mp3\""
    eval $cmd
}

### main

parse_opts "$@"
if test $convert_to_flac -ne 0
then
    which flac > /dev/null || bad_exit "cannot find \`flac' program, aborting."
fi
if test $convert_to_mp3 -ne 0
then
    which lame > /dev/null || bad_exit "cannot find \`lame' program, aborting."
fi
test -n "$output_dir" && mkdir -p "$output_dir"
for i in "${files[@]}"
do
    test $convert_to_flac -ne 0 && process_flac "$i"
    test $convert_to_mp3  -ne 0 && process_mp3  "$i"
done
